### ISSUE TITLE
[Bug]: only working on server after loading singleplayer first + ongoing log spam after loading singleplayer

### ISSUE THREAD

**Issue by Nycto97** [TeamDiopside/Seamless#14] opened 2023-10-19 02:02 UTC
### Latest Version

- [X] I am running the latest version of the mod.

### What happened?

1. Only works on dedicated server after loading in singleplayer first.
Launching game and joining dedicated server, without loading into a singleplayer world first, will cause the mod not to work.

2. Log spam as soon as loaded into singleplayer world
The moment I'm loaded into singleplayer, my client output starts spitting out errors at around 200 msgs / sec.
`[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_south does not exist!
[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_southeast does not exist!
[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:large_lilypad" from environmental:lilypad_southeast does not exist!
[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_southwest does not exist!
[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:large_lilypad" from environmental:lilypad_southwest does not exist!
[19Oct2023 03:23:26.135] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_west does not exist!
[19Oct2023 03:23:26.143] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_center does not exist!
[19Oct2023 03:23:26.143] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_east does not exist!
[19Oct2023 03:23:26.143] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_north does not exist!
[19Oct2023 03:23:26.143] [Render thread/ERROR] [Seamless/]: Block "environmental:giant_lilypad" from environmental:lilypad_northeast does not exist!`

Mods client: [client-mod-list_2023-10-19_03.01.32.txt](https://github.com/TeamDiopside/Seamless/files/13035566/client-mod-list_2023-10-19_03.01.32.txt)

Mods server: [server-mod-list_2023-10-19_03.33.29.txt](https://github.com/TeamDiopside/Seamless/files/13035576/server-mod-list_2023-10-19_03.33.29.txt)

Loading up game and joining dedicated server (not working, no log spam):
![2023-10-19_03 14 33](https://github.com/TeamDiopside/Seamless/assets/83367226/9ccb52b5-d159-4d94-900c-bb8235fc0387)

Loading up game and loading singleplayer world (working, log spam):
![2023-10-19_03 04 02](https://github.com/TeamDiopside/Seamless/assets/83367226/ee2448c9-4c4f-4917-b626-eebe488bfa33)
![image](https://github.com/TeamDiopside/Seamless/assets/83367226/83736275-c69f-494f-93d9-83ccd14893f4)

Joining dedicated server after loading singleplayer world first (working, log spam):
![2023-10-19_03 23 40](https://github.com/TeamDiopside/Seamless/assets/83367226/eccfd748-8096-44a3-ab1f-ff2c4ac71fdf)

### What did you expect to happen?

1. To have working connected outlines, provided by this mod, when joining multiplayer dedicated server, without the need to load into a singleplayer world first.

2. To not have log spam in client log.

### How to reproduce the bug?

1. Have this mod (+ the other listed mods above, if that makes a difference) installed.
2. Join server upon loading game and experience connected outlines not working.
3. Leave server and join singleplayer world and experience working connected outlines while also having log spam.
4. Leave singleplayer world and join server and experience working connected outlines while still having log spam.

### What version of Minecraft are you running?

1.19.2

### What mod loader are you using?

Forge

### latest.log

https://gist.github.com/Nycto97/a9536c2f176ca8ef9ea40d45db4092b8

**Comment by LarsMans64** [comment] 2023-10-21 22:26
I can't reproduce this with only Seamless, @Nycto97 could you try to find out which mod combination is causing this?

**Comment by Nycto97** [comment] 2023-10-22 23:12
Well, I would want to, and i just tried, but the problem is that I'm running 413 unique mods at the moment.
351 on client and 352 on server, combined 413 unique.

I have no idea where to start even. I wanted to use the binary search method, but with all the dependencies the mods have, and with the differences in client and server sided mods, I feel lost.

If it was testing on client only, it would be easy, even with dependencies, but i need to test client + server.

Any suggestions or tips?

**Comment by LarsMans64** [comment] 2023-10-22 23:17
Hmm yeah, binary search seems like the best method to me. I guess you don't really have a choice, sorry.

As for the server: you could just make a simple local hosted server for testing

**Comment by LarsMans64** [comment] 2023-10-22 23:21
You could start by separating the list into mods for client, server and both and then use binary search on each of the lists

**Comment by LarsMans64** [comment] 2023-10-22 23:27
By the way, your logs have no seamless errors

**Comment by curryducker** [comment] 2023-10-23 08:23
if you're talking about the SimpleJsonResourceReloadListener errors, those are caused by 'cgm' which is MrCrayfish's Gun Mod and not seamless. Seamless probably stops working because of resource loading errors and Seamless indeed needs resource loading. Try without cgm and let us know if the issue is still present :)

**Comment by Nycto97** [comment] 2023-10-23 13:30
Running game without cgm, additionalguns and alloyedguns, still same result when joining multiplayer server without loading singleplayer beforehand:
![image](https://github.com/TeamDiopside/Seamless/assets/83367226/b4dc173e-5061-4e0d-ab67-ae79100fdba3)

I will try do binary search, I really want to find what is causing this.

**Comment by Nycto97** [comment] 2023-10-23 19:31
Tried to do binary search, but going further with this will cost me a lot of time :(

I also tried to just load all mods on client and see how it behaves on an integrated server and it works just fine. I don't understand what's causing this and what differences there are between integrated server vs dedicated server in this situation.

**Comment by LarsMans64** [comment] 2023-10-23 19:36
You could check if the problem only occurs on that server or all dedicated servers

**Comment by Nycto97** [comment] 2023-10-23 19:58
I play on my own server. I don't play on any other server.
It must be a mod from my 'server mod list' causing this.

It's just too many mods. I hope one day someone makes a more narrowed down report of this issue. Maybe someone who has less mods than me.

**Comment by LarsMans64** [comment] 2023-11-11 19:13
I'm closing this for the time being, I hope the problem gets found eventually.

**Closed as completed** 2023-11-11 19:13 UTC
Labels: bug
